name: Python CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # ✅ Ensures submodules are pulled

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r Python/Py_Adv/Github_Action_Workflow/AI_Log_Analyzer/requirements.txt

      - name: Run tests
        run: pytest

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule sync --recursive
          git submodule update --remote --force --merge  # Force merge updates
          git config --local user.name "KPkm25"
          git config --local user.email "kumarparakram007@gmail.com"
          git add .
          git commit -m "Auto update AI_Log_Analyzer submodule" || echo "No changes to commit"
          git push origin main
      
