name: Python CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # ✅ Ensures submodules are pulled

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r Python/Py_Adv/Github_Action_Workflow/AI_Log_Analyzer/requirements.txt

      - name: Run tests
        run: pytest

      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://KPkm25:${{ secrets.DEVOPS_PAT }}@github.com/KPkm25/DevOps.git
          git add Python/Py_Adv/Github_Action_Workflow/AI_Log_Analyzer
          git commit -m "Auto update AI_Log_Analyzer submodule" || echo "No changes to commit"
          git push origin main
